Fixed bug 1420 - SDLNet_Read fails when passing a const pointer
Felix Geyer

SDLNet_Read16 and SDLNet_Read32 fail when passing a const pointer:
> error: reinterpret_cast from type 'const char*' to type 'Uint32* {aka unsigned int*}' casts away qualifiers

The actual SDLNet_Read* functions are only defined for "void *" but the macros previously allowed passing const pointers as they used c-style casts.

This can probably be fixed by casting to "const Uint16 *" / "const Uint32 *".